[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rust-crypto = "^0.2"
itertools = "0.10.3"
regex = "1.5"
fxhash = "0.2.1"